/**
 * Weekly API sync: fetches `${FABPLANE_API_ORIGIN:-https://api.fabplane.com}/v1/public/openapi.json`,
 * writes `spec/openapi.json`, regenerates `src/generated/operations.ts`, and reports operations
 * that have no `FabplaneClient` method yet.
 *
 *   node --experimental-strip-types scripts/sync-spec.ts [--offline]
 *
 * `--offline` skips the fetch and only regenerates from the committed spec. A 404 (the API does
 * not serve the document yet) or a network failure exits 0 without touching anything. Outputs
 * `changed`, `missing` and `report` for GitHub Actions when `GITHUB_OUTPUT` is set.
 */
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type Operation = { operationId: string; method: string; path: string };

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const specPath = join(root, "spec", "openapi.json");
const opsPath = join(root, "src", "generated", "operations.ts");
const clientPath = join(root, "src", "client.ts");
const METHODS = ["get", "put", "post", "delete", "patch", "head", "options"];

function setOutput(name: string, value: string): void {
  const file = process.env["GITHUB_OUTPUT"];
  if (!file) return;
  if (value.includes("\n")) appendFileSync(file, `${name}<<__EOF__\n${value}\n__EOF__\n`);
  else appendFileSync(file, `${name}=${value}\n`);
}

export function extractOperations(doc: unknown): Operation[] {
  const paths = (doc as { paths?: Record<string, Record<string, { operationId?: string }>> }).paths ?? {};
  const ops: Operation[] = [];
  for (const [path, item] of Object.entries(paths)) {
    for (const method of METHODS) {
      const op = item?.[method];
      if (op && typeof op.operationId === "string") ops.push({ operationId: op.operationId, method: method.toUpperCase(), path });
    }
  }
  return ops.sort((a, b) => a.path.localeCompare(b.path) || METHODS.indexOf(a.method.toLowerCase()) - METHODS.indexOf(b.method.toLowerCase()));
}

export function renderOperations(ops: Operation[]): string {
  const rows = ops.map((o) => `  { operationId: ${JSON.stringify(o.operationId)}, method: ${JSON.stringify(o.method)}, path: ${JSON.stringify(o.path)} },`);
  return [
    "// Generated by scripts/sync-spec.ts from spec/openapi.json. Do not edit by hand.",
    "",
    "export type OperationInfo = { operationId: string; method: string; path: string };",
    "",
    "export const operations: readonly OperationInfo[] = [",
    ...rows,
    "];",
    "",
  ].join("\n");
}

/** Method names declared on `FabplaneClient` (read from the source, so no build is needed). */
export function clientMethodNames(source: string): Set<string> {
  const names = new Set<string>();
  for (const m of source.matchAll(/^ {2}(?:async\s+)?([a-zA-Z_]\w*)\s*(?:<[^>]*>)?\(/gm)) if (m[1]) names.add(m[1]);
  return names;
}

async function fetchSpec(origin: string): Promise<unknown | null> {
  const url = `${origin.replace(/\/+$/, "")}/v1/public/openapi.json`;
  let res: Response;
  try {
    res = await fetch(url, { headers: { accept: "application/json" }, signal: AbortSignal.timeout(30_000) });
  } catch (err) {
    console.log(`sync-spec: cannot reach ${url} (${err instanceof Error ? err.message : String(err)}); skipping.`);
    return null;
  }
  if (res.status === 404) {
    console.log(`sync-spec: ${url} answered 404 (not deployed yet); skipping.`);
    return null;
  }
  if (!res.ok) {
    console.log(`sync-spec: ${url} answered HTTP ${res.status}; skipping.`);
    return null;
  }
  const doc = (await res.json().catch(() => null)) as { openapi?: unknown; paths?: unknown } | null;
  if (!doc || typeof doc.openapi !== "string" || typeof doc.paths !== "object") {
    console.log(`sync-spec: ${url} did not return an OpenAPI document; skipping.`);
    return null;
  }
  return doc;
}

async function main(): Promise<void> {
  const offline = process.argv.includes("--offline");
  const origin = process.env["FABPLANE_API_ORIGIN"] || "https://api.fabplane.com";
  const before = readFileSync(specPath, "utf8");
  let doc: unknown = JSON.parse(before);
  if (!offline) {
    const fetched = await fetchSpec(origin);
    if (fetched === null) {
      setOutput("changed", "false");
      return;
    }
    doc = fetched;
  }
  const specText = `${JSON.stringify(doc, null, 2)}\n`;
  const beforeOps = readFileSync(opsPath, "utf8");
  const ops = extractOperations(doc);
  const opsText = renderOperations(ops);
  writeFileSync(specPath, specText);
  writeFileSync(opsPath, opsText);

  const oldIds = new Set(extractOperations(JSON.parse(before)).map((o) => o.operationId));
  const newIds = new Set(ops.map((o) => o.operationId));
  const added = [...newIds].filter((id) => !oldIds.has(id));
  const removed = [...oldIds].filter((id) => !newIds.has(id));
  const methods = clientMethodNames(readFileSync(clientPath, "utf8"));
  const missing = ops.filter((o) => !methods.has(o.operationId));
  const changed = specText !== before || opsText !== beforeOps;

  const lines = [
    `Synced ${ops.length} operations from ${offline ? "spec/openapi.json" : origin}.`,
    added.length ? `Added: ${added.join(", ")}` : "Added: none",
    removed.length ? `Removed: ${removed.join(", ")}` : "Removed: none",
    missing.length
      ? `Missing FabplaneClient methods (${missing.length}):\n${missing.map((o) => `- \`${o.operationId}\` ${o.method} ${o.path}`).join("\n")}`
      : "Every operation has a FabplaneClient method.",
  ];
  const report = lines.join("\n");
  console.log(report);
  setOutput("changed", changed ? "true" : "false");
  setOutput("missing", String(missing.length));
  setOutput("report", report);
  const summary = process.env["GITHUB_STEP_SUMMARY"];
  if (summary) appendFileSync(summary, `## API sync\n\n${report}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
